task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('tasks.urls'))
]

tasks/urls.py
"""Определяет схемы URL для task."""

from django.urls import path
from . import views

app_name = 'tasks'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница со списком всех тем.
    path('tasks/', views.tasks, name='tasks'),
    # Страница с подробной информацией по отдельной теме
    path('tasks/<int:task_id>/', views.task, name='task'),
    # Страница для добавления новой темы
    path('new_task/', views.new_task, name='new_task'),
    # Страница для добавления новой записи
    path('new_entry/<int:task_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Task(models.Model):
    """Задача пользователя"""
    task_name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.task_name


class Entry(models.Model):
    """Описание задачи"""
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    start_time = models.DateField(auto_now_add=False)
    end_time = models.DateField(auto_now_add=False)
    completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=10, choices=(
        ("high", "High"), ("medium", "Medium"), ("low", "Low")))

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        return f"{self.task}"

users/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django import forms
from .models import Task, Entry


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name']
        labels = {'task_name': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['start_time', 'end_time', 'completed', 'priority']
        labels = {'start_time': 'Start Time', 'end_time': 'End_Time',
                  'completed': 'Completed', 'priority': 'Priority'}
        widgets = {'start_time': forms.DateInput(
            attrs={'type': 'date'}), 'end_time': forms.DateInput(attrs={'type': 'date'})}

tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Task, Entry
from .forms import TaskForm, EntryForm
# Create your views here.


def index(request):
    """Домашняя страница приложения Task"""
    return render(request, 'tasks/index.html')


@login_required
def tasks(request):
    """Выводит список тем."""
    tasks = Task.objects.filter(owner=request.user).order_by('task_name')
    context = {'tasks': tasks}
    return render(request, 'tasks/tasks.html', context)


@ login_required
def task(request, task_id):
    """Выводит одну задачу и все ее записи."""
    task = Task.objects.get(id=task_id)
    # Проверка того, что тема принадлежит текущему пользователю.
    if task.owner != request.user:
        raise Http404
    entries = task.entry_set.order_by('start_time')
    context = {'task': task, 'entries': entries}
    return render(request, 'tasks/task.html', context)


@ login_required
def new_task(request):
    """Определяет новую задачу."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TaskForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TaskForm(data=request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return redirect('tasks:tasks')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'tasks/new_task.html', context)


@ login_required
def new_entry(request, task_id):
    """Добавляет новую запись по конкретной задаче."""
    task = Task.objects.get(id=task_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.task = task
            new_entry.save()
            return redirect('tasks:task', task_id=task_id)
    # Вывести пустую или недействительную форму.
    context = {'task': task, 'form': form}
    return render(request, 'tasks/new_entry.html', context)


@ login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    task = entry.task
    if task.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('tasks:task', task_id=task.id)
    context = {'entry': entry, 'task': task, 'form': form}
    return render(request, 'tasks/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('learning_logs:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

tasks/templates/tasks/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Task</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
	<a class="navbar-brand" href="{% url 'tasks:index' %}">
		Task</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span></button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'tasks:tasks' %}">
					Tasks</a></li>
		</ul>
		<ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text"> Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<form action="{% url 'users:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-light">log out</button>
                        </form>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
<main role="main" class="container">
	<div class="pb-2 mb-2 border-bottom">
		{% block page_header %}{% endblock page_header %}
	</div>
	<div>
		{% block content %}{% endblock content %}
	</div>
</main>
</body>
</html>

tasks/templates/tasks/edit_entry.html
{% extends "tasks/base.html" %}
{% block content %}
	<p><a href="{% url 'tasks:task' task.id %}">{{ task }}</a></p>
	<p>Edit entry:</p>
		<form action="{% url 'tasks:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">save changes</button>
	</form>
{% endblock content %}

tasks/templates/tasks/index.html
{% extends "tasks/base.html" %}
{% block content %}
    <p>Task helps you!</p>
{% endblock content %}

tasks/templates/tasks/new_entry.html
{% extends "tasks/base.html" %}
{% block content %}
  <p><a href="{% url 'tasks:task' task.id %}">{{ task }}</a></p>
  <p>Add a new entry:</p>
  <form action="{% url 'tasks:new_entry' task.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit'>add entry</button>
  </form>
{% endblock content %}

tasks/templates/tasks/new_task.html
{% extends "tasks/base.html" %}
{% block content %}

	<p>Add a new task:</p>
	<form action="{% url 'tasks:new_task' %}" method='post'>
	{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">add task</button>
	</form>

{% endblock content %}

tasks/templates/tasks/task.html
{% extends 'tasks/base.html' %}
{% block content %}
  <p>Task: {{ task }}</p>
  <p>Entries:</p>
  <p>
    <a href="{% url 'tasks:new_entry' task.id %}">add new entry</a>
  </p>
  <ul>
  {% for entry in entries %}
    <li>
      <p>{{ entry.start_time|date:'M d, Y' }}</p>
      <p>{{ entry.end_time|date:'M d, Y' }}</p>
      {% if entry.completed != True %}
        <input type="checkbox" disabled /> <label>No completed</label>
      {% else %}
        <input type="checkbox" disabled checked/> <label>Completed</label>
      {% endif %}
      <p>Prioritet: --{{ entry.priority }}--</p>
      <p>
        <a href="{% url 'tasks:edit_entry' entry.id %}">Edit entry</a>
    </p>
    </li>
  {% empty %}
    <li>There are no entries for this task yet ¯\_(ツ)_/¯</li>
  {% endfor %}
  </ul>
{% endblock content %}

tasks/templates/tasks/tasks.html
{% extends "tasks/base.html" %}
{% block content %}
  <p>Tasks</p>
  <ul>
    {% for task in tasks %}
        <li>
            <a href="{% url 'tasks:task' task.id %}">{{ task }}</a>
        </li>
    {% empty %}
      <li>No tasks ¯\_(ツ)_/¯</li>
    {% endfor %}
  </ul>
  <a href="{% url 'tasks:new_task' %}">Add a new task:</a>
{% endblock content %}